#-------------------------------
# General Site Settings

title: BRASHCITY
blog-title: BRASHCITY
description: SHOCKING THE WORLD WITH STIMULATING ENTERTAINMENT!
email: Futuristicdigital01@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Us, url: '#about-me'}
- {name: Roofing, url: '/services'}
- {name: Exterior Services, url: '#contact'}
- {name: Gallery, url: '/blog'}
- {name: Contact Us, url: '/blog'}

servicesmenu:
- {name: About Me, url: '/'}
- {name: Services, url: '/services'}
- {name: Contact, url: '/#contact'}
- {name: Blog, url: '/blog'}

blogmenu:
- {name: Web Design, url: '/blog/webdesign'}
- {name: SEO, url: '/blog/seo'}
- {name: Advertising, url: '/blog/advertising'}
- {name: Web Design, url: '/blog/webdesign'}
- {name: SEO, url: '/blog/seo'}
- {name: Advertising, url: '/blog/advertising'}
- {name: Home, url: '/'}


#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'World's most shocking entertainment'
  rel-author: 'https://www.facebook.com/brashcity'
  rel-publisher: 'https://www.facebook.com/brashcity'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

# Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
# but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
#  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen.



# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
